I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00keymap.rpy", line 459, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 459, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 478, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
AttributeError: 'NoneType' object has no attribute 'stores'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00keymap.rpy", line 459, in script
    python hide:
  File "renpy/ast.py", line 913, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2111, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00keymap.rpy", line 459, in <module>
    python hide:
  File "renpy/common/00keymap.rpy", line 478, in _execute_python_hide
    renpy.save("_reload-1", "reload save game")
  File "renpy/loadsave.py", line 392, in save
    roots = renpy.game.log.freeze(None)
  File "renpy/python.py", line 2008, in freeze
    self.complete(False)
  File "renpy/python.py", line 1614, in complete
    self.current.stores[name], self.current.delta_ebc[name] = sd.get_changes(begin)
AttributeError: 'NoneType' object has no attribute 'stores'

