I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/main_menu.rpy", line 13, in script
    python hide:
<<<<<<< HEAD
  File "renpy/common/00keymap.rpy", line 459, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 459, in <module>
=======
  File "game/main_menu.rpy", line 13, in script
>>>>>>> 1bc5a6c59f0432742f6081b657dea4436bac35d0
    python hide:
  File "game/main_menu.rpy", line 13, in <module>
    python hide:
  File "game/main_menu.rpy", line 19, in _execute_python_hide
    'Quit Game' : dict(xpos=550, ypos=490, xanchor='left', yanchor='top'),
Exception: config.main_menu_positions is not a known configuration variable.

-- Full Traceback ------------------------------------------------------------

Full traceback:
<<<<<<< HEAD
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/main.py", line 505, in main
    if renpy.parser.report_parse_errors():
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/parser.py", line 2955, in report_parse_errors
    renpy.display.error.report_parse_errors(full_text, error_fn)
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/display/error.py", line 192, in report_parse_errors
    error_fn=error_fn,
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/game.py", line 282, in invoke_in_new_context
    return callable(*args, **kwargs)
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/display/error.py", line 46, in call_exception_screen
    return renpy.ui.interact(mouse="screen", type="screen", suppress_overlay=True, suppress_underlay=True)
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/display/core.py", line 2978, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/display/core.py", line 3441, in interact_core
    renpy.loader.check_autoreload()
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/loader.py", line 1097, in check_autoreload
    renpy.exports.reload_script()
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/exports.py", line 1810, in reload_script
    renpy.game.call_in_new_context("_save_reload_game")
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/game.py", line 333, in call_in_new_context
    return renpy.execution.run_context(False)
  File "/Users/user/Desktop/renpy-7.4.0-sdk/renpy/execution.py", line 922, in run_context
    context.run()
  File "renpy/common/00keymap.rpy", line 459, in script
    python hide:
  File "renpy/common/00keymap.rpy", line 459, in script
=======
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 515, in main
    renpy.game.context().run(node)
  File "game/main_menu.rpy", line 13, in script
    python hide:
  File "game/main_menu.rpy", line 13, in script
>>>>>>> 1bc5a6c59f0432742f6081b657dea4436bac35d0
    python hide:
  File "renpy/ast.py", line 913, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2111, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/main_menu.rpy", line 13, in <module>
    python hide:
  File "game/main_menu.rpy", line 19, in _execute_python_hide
    'Quit Game' : dict(xpos=550, ypos=490, xanchor='left', yanchor='top'),
  File "renpy/defaultstore.py", line 106, in __setattr__
    raise Exception('config.%s is not a known configuration variable.' % (name))
Exception: config.main_menu_positions is not a known configuration variable.

